### ISSUE TITLE
Bug when select value in 2 object of attribute slicer

### ISSUE THREAD

**Issue by kleinos** [Microsoft/PowerBI-visuals-AttributeSlicer#30]
I have 2 object of attribute slice in my application, when value in the first object is selected, everything going well, but when i select one value in the second object, then something going wrong, selected value in the second object is like select-hide-select-hide. 

Hope this bug can fix soon, because i really need this object.

try on attribute slicer version 0.12.1

Note: attribute slicer version 0.11.6 is good, but i need thousand delimiter in the value, so i have to modification in your code, but in version 0.11.6, i can't build this object because one of your library is missing (essex.powerbi.base)

thank you.

**Comment by stopyoukid** [comment]
You are correct, there are issues with having multiple attribute slicers working together on the same report right now.  In 0.12.x we switched over to using "highlighting" and the SelectionManager to support a large feature set that we were developing.  However, in doing so, we lost the ability to support multiple attribute slicers on the same report.  We are working with the PowerBI team to figure out a solution to the problem.

In the meantime, I've created an 0.11.x branch, with the fixes for "essex.powerbi.base" (it is now called `@essex/pbi-base`), and it should build for you.

**Comment by stopyoukid** [comment]
Also, I forgot to mention, you should be able to tweak the value display by using the formatting pane.  See image below:

![image](https://cloud.githubusercontent.com/assets/2513737/22657113/2a83626c-ec4a-11e6-9e50-9905cbeb71bb.png)

Under Display, there is "Visual_DisplayUnits" and "Visual_Precision", which allow you to control how the value is formatted.

**Comment by kleinos** [comment]
thank you for your fast response, you really help me a lot

**Comment by kleinos** [comment]
sorry for asking, is there any news for my issue ? or this issue is not happen to your object ?
i just need to verify that this issue came from your code

thank you

**Comment by stopyoukid** [comment]
Oh, I didn't see your comment change.  I've pushed a change to the 0.11.x branch, it should fix your selection issue.  In regards to the bars not looking correct -- the problem with the gallery version is that it assumes that in your dataset the minimum value for your "Values" column...

![image](https://cloud.githubusercontent.com/assets/2513737/22833557/3f3bc2a6-ef67-11e6-9087-7dc5bbe23c73.png)

 is `0`, but that isn't necessarily correct.  If you passed in column that contained negative values, then the bar lengths would be incorrect because the minimum is not 0.  However, in 0.11.x, it is actually scaling correctly, the one with the minimum value effectively gets the `0%` width bar and the largest value gets the `100%` width bar, although it isn't very nice to look at.  The whole problem stems from the fact that the visual cannot see the entire dataset to effectively determine what the min/max values are for that column, so it just uses what data is given to it from powerbi to determine it.

That being said, you can tweak it to change that minimum value, the easiest way would be to change these lines: https://github.com/Microsoft/PowerBI-visuals-AttributeSlicer/blob/0.11.x/src/powerbi/AttributeSlicerVisual.ts#L191-L193

The `c.renderedValue` line is where it is doing the scaling.  `minValue` is the minimum value it found, `maxValue` is the maximum value it found.  So, if you just change the `minValue` to be 0, then everything should look like it did originally.

Quick Note: `c.renderedValue` is the width of the bar that you want, so a value of `50` would make a `50%` width bar.

**Comment by kleinos** [comment]
you really help me, now everything going well

thank you so much.

**Comment by stopyoukid** [comment]
Fixed by #36
