### ISSUE TITLE
"Shift select" feature appears to have broken in July 2017 Power BI update

### ISSUE THREAD

**Issue by mpiecyk** [Microsoft/PowerBI-visuals-AttributeSlicer#52]
The "Shift select" feature appears to have broken in July 2017 Power BI update. When Single Select and Brush Select are both off, it used to be possible to click an item, hold Shift, click another item, and select multiple items.

Now, just the items which are clicked are selected. So, if a user wants to select 100 items, they would need to click 100 times.

**Comment by ericleigh007** [comment]
Confirmed. this is a real pain and needs to be high priority.  Thx

**Comment by eric-kimbrel** [comment]
Was able to reproduce and have some additional details.

When an item in the list is clicked the window looses focus, the blur event fires, and we stop seeing keyup/keydown events. Once we click away from the visual the Window gets focus and key events can be seen again.  As a result the shift selection doesn't work because the visual is unable to detect that the shift key was pressed.

More research is required to figure out exactly what the cause of this change was and how we can fix it, in the meantime I might suggest using brush selection as an alternative.

**Comment by mpiecyk** [comment]
Thanks for taking a look and being very responsive to your list of issues.

**Comment by ericleigh007** [comment]
Could be for short lists, but the brush selection stops selecting when the list scrolls, in my experience.   We are trying to select 20 items in our use case, and the list window is sized o only show a few, to save space for visuals

Thx.

Sent from my Windows 10 phone

**Comment by eric-kimbrel** [comment]
Fixed in the develop branch, will be fixed in the v1.0.3 release
